# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
# │
# ├
# └─
# ┤
# ╼
# ╢
# ║
# ╓
# ─
format = """
([╓─────────────────](bold blue)
([╟╴](bold blue)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\n)\
([╟╴](bold blue)\
$rust\
$python\
$golang\
$haskell\n)\
[╚╡](bold blue))$directory$character
"""

[cmd_duration]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[aws]
disabled = true

# SOURCES

# Replace the "❯"
[character]
success_symbol = "[❯](blue bold)"
error_symbol = "[❯](red bold)"
disabled = false

# truncation length works backwards (i.e., cwd > parent > parent ...)
[directory]
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = true

# Show python version starting with venv
[python]
python_binary = ["./venv/bin/python", "python3", "python", "python2"]

[rust]
disabled = false

[docker_context]
disabled = false

[gcloud]
disabled = true

[os]
format = '[$symbol](bold white)'
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
