#!/bin/sh

wifi=$(nmcli -t device wifi list | grep "*" | awk -F ":" '{printf "%s %s", $8, $12}')

icon() {
  if [ -z "$wifi" ]; then
    echo "󰤯" && exit
  fi

  if [ $1 -gt 100 ]; then
    echo "󰤨"
  elif [ $1 -gt 75 ]; then
    echo "󰤥"
  elif [ $1 -gt 50 ]; then
    echo "󰤢"
  elif [ $1 -gt 25 ]; then
    echo "󰤟"
  fi
}

signal() {
    if [ -z "$wifi" ]; then
    echo "Disconnected" && exit
    fi

  echo $wifi | awk '{print $2}'
}

name() {
    if [ -z "$wifi" ]; then
    echo "Disconnected" && exit
    fi

  echo $wifi | awk '{print $1}'
}

case $1 in
  "name")
    name
    ;;
  "signal")
    signal
    ;;
  "icon")
    icon $(signal)
esac