#!/bin/sh

workspaces() {
    un="-"
    ws1=0
    ws2=1
    ws3=2
    ws4=3
    ws5=4
    ws6=5
    ws7=6
    ws8=7
    ws9=8

    # check if Occupied
    occupied=$(wmctrl -l | awk '{print $2}'  | uniq)
    o1=$(echo "$occupied" | grep $ws1)
    o2=$(echo "$occupied" | grep $ws2)
    o3=$(echo "$occupied" | grep $ws3)
    o4=$(echo "$occupied" | grep $ws4)
    o5=$(echo "$occupied" | grep $ws5)
    o6=$(echo "$occupied" | grep $ws6)
    o7=$(echo "$occupied" | grep $ws7)
    o8=$(echo "$occupied" | grep $ws8)
    o9=$(echo "$occupied" | grep $ws9)

    # check if focused
    focused=$(wmctrl -d | awk '{if ($2=="*") print $1}')
    f1=$(echo "$focused" | grep $ws1)
    f2=$(echo "$focused" | grep $ws2)
    f3=$(echo "$focused" | grep $ws3)
    f4=$(echo "$focused" | grep $ws4)
    f5=$(echo "$focused" | grep $ws5)
    f6=$(echo "$focused" | grep $ws6)
    f7=$(echo "$focused" | grep $ws7)
    f8=$(echo "$focused" | grep $ws8)
    f9=$(echo "$focused" | grep $ws9)

    # generate yuck
echo "\
(box :class \"workspaces\" :space-evenly \"false\" :spacing \"0\" \
(button :class \"$un${o1:=-}${f1:=-}\" :onclick \"wmctrl -s $ws1\" \"\")  \
(button :class \"$un${o2:=-}${f2:=-}\" :onclick \"wmctrl -s $ws2\" \"󰈹\")  \
(button :class \"$un${o3:=-}${f3:=-}\" :onclick \"wmctrl -s $ws3\" \"󰓓\")  \
(button :class \"$un${o4:=-}${f4:=-}\" :onclick \"wmctrl -s $ws4\" \"󰺿\")  \
(button :class \"$un${o5:=-}${f5:=-}\" :onclick \"wmctrl -s $ws5\" \"󰝚\")  \
(button :class \"$un${o6:=-}${f6:=-}\" :onclick \"wmctrl -s $ws6\" \"6\")  \
(button :class \"$un${o7:=-}${f7:=-}\" :onclick \"wmctrl -s $ws7\" \"7\")  \
(button :class \"$un${o8:=-}${f8:=-}\" :onclick \"wmctrl -s $ws8\" \"8\")  \
(button :class \"$un${o9:=-}${f9:=-}\" :onclick \"wmctrl -s $ws9\" \"9\"))"
}

focused() {
    wmctrl -d | awk '{if ($2=="*") print $1}'
}

if [[ $1 == "test" ]]; then
    workspaces; exit
fi

workspaces
while true
do
workspaces
done