#!/bin/bash

workspaces() {
    un="0"
    ws1=0
    ws2=1
    ws3=2
    ws4=3
    ws5=4
    ws6=5
    ws7=6
    ws8=7
    ws9=8

    # check if Occupied
    occupied=$(wmctrl -l | awk '{print $2}'  | uniq | tr -d '\n')

    # check if focused
    focused=$(wmctrl -d | awk '{if ($2=="*") print $1}')

    # generate yuck
echo "(box :class \"workspaces\" :space-evenly \"false\" :spacing \"10\" (button :class \"button1\" :onclick \"wmctrl -s $ws1\") \"1\" (button :class \"button2\" :onclick \"wmctrl -s $ws2\") \"2\" (button :class \"button3\" :onclick \"wmctrl -s $ws3\") \"3\" (button :class \"button4\" :onclick \"wmctrl -s $ws4\") \"4\" (button :class \"button5\" :onclick \"wmctrl -s $ws5\") \"5\" (button :class \"button6\" :onclick \"wmctrl -s $ws6\") \"6\" (button :class \"button7\" :onclick \"wmctrl -s $ws7\") \"7\" (button :class \"button8\" :onclick \"wmctrl -s $ws8\") \"8\" (button :class \"button9\" :onclick \"wmctrl -s $ws9\") \"9\")"
}

focused() {
    wmctrl -d | awk '{if ($2=="*") print $1}'
}

workspaces
while true
do
workspaces
sleep 1
done